import { StyleSheet } from 'react-native';
import { Theme } from '../../../constants/theme';

export const createHeaderStyles = (theme: Theme, isRTL: boolean = false) =>
  StyleSheet.create({
    container: {
      marginBottom: theme.spacing.xl,
    },
    banner: {
      width: '100%',
      height: theme.sizes.banner.height,
      backgroundColor: theme.colors.background.tertiary,
      position: 'relative',
    },
    avatar: {
      width: theme.sizes.avatar.md,
      height: theme.sizes.avatar.md,
      borderRadius: theme.sizes.avatar.md / 2,
      borderWidth: 4,
      borderColor: theme.colors.background.primary,
      marginTop: -theme.spacing.xxl,
      zIndex: 5,
    },
    imageContainer: {
      flexDirection: isRTL ? 'row-reverse' : 'row',
      width: '100%',
      justifyContent: 'space-between',
      paddingHorizontal: theme.spacing.lg,
      alignItems: 'flex-start',
      zIndex: 5,
    },
    editButton: {
      backgroundColor: theme.colors.background.primary,
      borderWidth: 1,
      borderColor: theme.colors.text.link,
      borderRadius: theme.spacing.xl,
      paddingHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.sm,
      marginTop: theme.spacing.md,
      justifyContent: 'center',
      alignItems: 'center',
    },
    messageButton: {
      backgroundColor: theme.colors.background.primary,
      borderWidth: 1,
      borderColor: theme.colors.text.primary + '40',
      borderRadius: theme.borderRadius.full,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      marginTop: theme.spacing.md,
      ...(isRTL ? { marginLeft: theme.spacing.sm } : { marginRight: theme.spacing.sm }),
      justifyContent: 'center',
      alignItems: 'center',
      minWidth: 40,
    },
    buttonsContainer: {
      flexDirection: isRTL ? 'row-reverse' : 'row',
      marginTop: theme.spacing.md,
    },
    viewPostsButton: {
      backgroundColor: theme.colors.text.link,
      borderWidth: 1,
      borderColor: theme.colors.text.link,
      borderRadius: theme.spacing.xxll,
      paddingHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.sm,
      marginTop: theme.spacing.md,
      textAlign: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      width: '60%',
      height: '22%',
    },
    viewPostsText: {
      color: theme.colors.text.inverse,
      fontWeight: theme.typography.weights.semiBold,
      textAlign: 'center',
      width: '100%',
    },
    followingButton: {
      backgroundColor: theme.colors.text.link,
      borderColor: theme.colors.text.link,
    },
    backButton: {
      backgroundColor: `rgba(0, 0, 0, ${theme.opacity.translucent - 0.2})`,
      width: theme.sizes.icon.lg + theme.spacing.xs * 3,
      height: theme.sizes.icon.lg + theme.spacing.xs * 3,
      borderRadius: (theme.sizes.icon.lg + theme.spacing.xs * 3) / 2,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      top: theme.spacing.xxxl + 5,
      ...(isRTL ? { right: theme.spacing.xl } : { left: theme.spacing.xl }),
    },
    actionsButton: {
      backgroundColor: `rgba(0, 0, 0, ${theme.opacity.translucent - 0.2})`,
      width: theme.sizes.button.height,
      height: theme.sizes.button.height,
      borderRadius: theme.sizes.button.borderRadius,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      top: theme.spacing.xxxl + 5,
      ...(isRTL ? { left: theme.spacing.xl } : { right: theme.spacing.xl }),
    },
    editText: {
      color: theme.colors.text.link,
      fontWeight: theme.typography.weights.semiBold,
    },
    followingText: {
      color: theme.colors.background.primary,
    },
    followsYouContainer: {
      backgroundColor: theme.colors.background.tertiary,
      alignSelf: 'flex-start',
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs / 2,
      borderRadius: theme.borderRadius.sm,
      marginTop: theme.spacing.xs,
    },
    followsYouText: {
      color: theme.colors.text.secondary,
      fontSize: theme.typography.sizes.xs,
    },
    nameContainer: {
      flexDirection: isRTL ? 'row-reverse' : 'row',
      alignItems: 'center',
      gap: theme.spacing.md,
      alignSelf: isRTL ? 'flex-end' : 'flex-start',
    },
    info: {
      paddingHorizontal: theme.spacing.lg,
      marginTop: theme.spacing.md - 4,
      alignItems: isRTL ? 'flex-end' : 'flex-start',
    },
    loadingContainer: {
      marginTop: theme.spacing.lg,
      alignItems: 'center',
    },
    name: {
      fontSize: theme.typography.sizes.lg,
      fontWeight: theme.typography.weights.bold,
      color: theme.colors.text.primary,
      textAlign: isRTL ? 'right' : 'left',
      alignSelf: isRTL ? 'flex-end' : 'flex-start',
    },
    handle: {
      color: theme.colors.text.secondary,
      marginBottom: theme.spacing.sm,
      textAlign: isRTL ? 'right' : 'left',
    },
    bio: {
      fontSize: theme.typography.sizes.sm - 1,
      color: theme.colors.text.primary,
      marginBottom: theme.spacing.xs,
      textAlign: isRTL ? 'right' : 'left',
    },
    link: {
      fontSize: theme.typography.sizes.xs - 1,
      color: theme.colors.text.link,
      marginBottom: theme.spacing.sm,
      textAlign: isRTL ? 'right' : 'left',
    },
    stats: {
      flexDirection: isRTL ? 'row-reverse' : 'row',
    },
    stat: {
      fontSize: theme.typography.sizes.sm - 1,
      color: theme.colors.text.primary,
    },
    statWithMargin: {
      fontSize: theme.typography.sizes.sm - 1,
      color: theme.colors.text.primary,
      ...(isRTL ? { marginRight: theme.spacing.md - 2 } : { marginLeft: theme.spacing.md - 2 }),
    },
    bold: {
      fontWeight: theme.typography.weights.bold,
    },
  });

export default createHeaderStyles;
